/**
 * @author Calder Coalson
 * @date   2019-03-01
 */
#ifndef GRPC_CLIENT_H
#define GRPC_CLIENT_H
#include "src/bullwinkle/all/GroundTelemetryRelay.h"
#include "src/bullwinkle/all/SlateBuilder.h"
#include "src/bullwinkle/all/UniqueIdGenerator.h"
#include "src/bullwinkle/all/async/DeferredCallbackQueue.h"
#include "src/bullwinkle/all/core/fswtime.h"
#include "src/bullwinkle/all/grpc/gRPC_endpoint.h"
#include "src/bullwinkle/all/grpc/gRPC_util.h"
#include "src/bullwinkle/all/hsm/SslPrivateKeyMethod.h"
#include <functional>
#include <grpc++/grpc++.h>
#include <grpc++/support/async_unary_call.h>
struct GrpcClientHarness;
void gpr_global_config_set_grpc_poll_strategy(const char *value);
void gpr_global_config_set_grpc_dns_resolver(const char *value);
namespace Drone
{
    /**
     * Asynchronous gRPC client interface.
     *
     * @tparam TService  Protobuf service type.
     * @tparam TRequest  Protobuf request type.
     * @tparam TResponse Protobuf response type.
     */
    template <typename _TService, typename _TRequest, typename _TResponse>
    class GrpcClientInterface
    {
    public:
        /**
         * Protobuf service type. Used for template reflection.
         */
        using TService = _TService;
        /**
         * Protobuf response type. Used for template reflection.
         */
        using TResponse = _TResponse;
        /**
         * Protobuf request type. Used for template reflection.
         */
        using TRequest = _TRequest;
        virtual ~GrpcClientInterface() = default;
        /**
         * Return type of the autogenerated Async* method.
         */
        using TRPC = std::unique_ptr<
            grpc::ClientAsyncResponseReaderInterface<TResponse>>;
        /**
         * Stub interface type.
         */
        using StubInterface = typename TService::StubInterface;
        /**
         * Type of the autogenerated Async* method.
         *
         * std::function rather than Slot because the target is an
         * automatically generated stub which is not a SignalHandler.
         */
        using TMethod =
            std::function<TRPC(StubInterface *, grpc::ClientContext *,
                               const TRequest &, grpc::CompletionQueue *)>;
        /**
         * Type of user supplied callbacks.
         *
         * std::function rather than Slot for consistency with TMethod.
         *
         * WARNING: Because many callers will still pass Slot callbacks,
         *          callbacks must not be copied outside of the main thread.
         */
        using TCallback = std::function<bool(grpc::Status, TResponse)>;
        /**
         * Start RPC and run callback on the main thread when done.
         *
         * WARNING: Must be called from the main thread.
         *
         * @param request  Protobuf request object.
         * @param callback Function to run on the main thread when RPC finishes.
         *
         * @return True if the call was started sucessfully, false otherwise.
         */
        virtual bool async(const TRequest &request, TCallback callback) = 0;
        /**
         * Set a new gRPC client timeout.
         * This is an optional function that will Fsw if not implemented in the
         * inherited class.
         *
         * @param new_timeout New gRPC client timeout.
         *
         * @return True if a new valid timeout was applied.
         */
        virtual bool set_timeout(const nano_t new_timeout)
        {
            FswAbort("Unimplemented optional function. Add functionality to "
                     "inherited class.",
                     false);
        }
        /**
         * Attempt to cancel all in-flight GRPC calls via the ClientContext's
         * TryCancel() interface.
         *
         * Makes no guarantees that calls are actually cancelled.
         */
        virtual void cancel_all_outstanding() = 0;
    };
    /**
     * Asynchronous gRPC client.
     *
     * Example usage
     * =============
     *
     *   // Create a DeferredCallbackQueue and register it with the EventLoop.
     *   EventLoop eloop;
     *   Handle<DeferredCallbackQueue> callback_queue =
     *       DeferredCallbackQueue::create(eloop.fds);
     *
     *   // Create the client.
     *   SlateBuilder slate;
     *   auto client = create_gprc_client<PumpService>(
     *           std::make_shared<StaticGrpcEndpoint>(GrpcEndpoint{.grpc_endpoint
     * = "endpoint"}), gprc::InsecureChannelCredentials(), *callback_queue,
     *           &PumpStubInterface::AsyncPumpQueue,
     *           slate);
     *
     *
     *   // Start an async RPC and run a callback when it completes.
     *   // Callback is run on the main thread via the DeferredCallbackQueue.
     *   FooRequest request;
     *   client->async(request, make_slot(*this, &Foo::on_response));
     *
     *
     * @tparam TRequest  Protobuf request type.
     * @tparam TResponse Protobuf response type.
     */
    template <typename TService, typename TRequest, typename TResponse>
    class GrpcClient : public GrpcClientInterface<TService, TRequest, TResponse>
    {
    public:
        using TRPC =
            typename GrpcClientInterface<TService, TRequest, TResponse>::TRPC;
        using TMethod = typename GrpcClientInterface<TService, TRequest,
                                                     TResponse>::TMethod;
        using TCallback = typename GrpcClientInterface<TService, TRequest,
                                                       TResponse>::TCallback;
        using StubInterface = typename TService::StubInterface;
        using StubFactoryInterface = GrpcStubFactoryInterface<TService>;
        /**
         * Static constructor.
         *
         * @note The create_grpc_client free function infers most template
         *       arguments and may be more convenient.
         *
         * @param _endpoint_provider     Provides the service endpoint.
         * @param _callback_queue        Runs callbacks on the main thread.
         * @param _method                Async* method to call.
         * @param builder                Slate builder.
         * @param _timeout               Timeout for all calls. Default one
         *                               second.
         * @param _max_outstanding_calls Max in-flight calls at any time.
         *                               Default 1.
         * @param flow                   Optional telemetry flow for metrics.
         * @param _stub_factory          Optional factory to create new stubs.
         *                               If null, GrpcStubFactory<Interface>
         *                               will be used.
         */
        static Handle<GrpcClient> create(
            std::shared_ptr<GrpcEndpointProviderInterface> _endpoint_provider,
            DeferredCallbackQueue &_callback_queue, TMethod _method,
            SlateBuilder &builder, const nano_t _timeout = billion,
            const size_t _max_outstanding_calls = 1,
            GroundNumericFlow *flow = nullptr,
            std::shared_ptr<StubFactoryInterface> _stub_factory = {})
        {
            Handle<GrpcClient> client(new GrpcClient(
                _endpoint_provider, _stub_factory, _callback_queue,
                std::move(_method), _timeout, _max_outstanding_calls));
            FswAbortIfNot(client, Handle<GrpcClient>());
            FswAbortIfNot(client->init(builder, flow), Handle<GrpcClient>());
            return client;
        }
        /**
         * Destructor.
         */
        virtual ~GrpcClient()
        {
            completion_queue.Shutdown();
            worker_thread.join();
        }
        /**
         * Start RPC and run callback on the main thread when done.
         *
         * WARNING: Must be called from the main thread.
         *
         * @param request  Protobuf request object.
         * @param callback Function to run on the main thread when RPC finishes.
         *
         * @return True if the call was skipped or started sucessfully, false
         * otherwise.
         */
        bool async(const TRequest &request, TCallback callback) override
        {
            FswAbortIfNot(callback, false);
            /*
             * Create a new stub on the first call to `async`.
             *
             * This is expected to only be for the very first call to this
             * function since stub recreation should only occur in the
             * completion callback once the RPC is complete (the stub needs to
             * remain alive/valid until the call completes).
             */
            if (!stub)
            {
                stub_factory->NewStub(*endpoint_provider, stub, true);
            }
            /*
             * Bail out if no stub is provided.
             */
            FswAbortIfNot(stub, false);
            /*
             * Bail out if we already have the max number of calls in flight.
             */
            if (slate[metric_count_outstanding_tok] >= max_outstanding_calls)
            {
                ++slate[metric_count_skipped_tok];
                return true;
            }
            /*
             * Prepare the async RPC.
             */
            std::unique_ptr<Call> call = std::make_unique<Call>(
                stub.get(), timeout, request, completion_queue, method,
                std::move(callback));
            FswAbortIfNot(call, false);
            FswAbortIfNot(call->rpc, false);
            /*
             * Start the RPC.
             */
            const uintptr_t tag = ++last_tag;
            call->rpc->Finish(&call->response, &call->status,
                              reinterpret_cast<void *>(tag));
            ++slate[metric_count_started_tok];
            /*
             * Store the RPC for later completion.
             */
            outstanding_calls.emplace(tag, std::move(call));
            ++slate[metric_count_outstanding_tok];
            return true;
        }
        /**
         * Set a new gRPC client timeout.
         * Expects a timeout that is a second or greater.
         *
         * @param new_timeout New gRPC client timeout.
         *
         * @return True if a new valid timeout was applied.
         */
        bool set_timeout(const nano_t new_timeout) override
        {
            FswMsgAbortIf(
                new_timeout < billion, false, 64,
                "gRPC timeout is less than the allowed minimum of 1s.");
            timeout = new_timeout;
            return true;
        }
        /**
         * Attempt to cancel all in-flight GRPC calls via the ClientContext's
         * TryCancel() interface.
         *
         * Makes no guarantees that calls are actually cancelled.
         */
        void cancel_all_outstanding() override
        {
            for (const auto &kv : outstanding_calls)
            {
                Call &call = *kv.second;
                call.context.TryCancel();
            }
        }

    private:
        /**
         * An in-flight remote procedure call.
         */
        struct Call
        {
            /**
             * Constructor.
             *
             * @param stub             Stub on which this call is made.
             * @param timeout          Timeout for the call.
             * @param request          Protobuf request message.
             * @param completion_queue gRPC queue to service responses on.
             * @param method           Async* method to call.
             * @param _callback        User callback to run on completion.
             */
            Call(StubInterface *stub, const nano_t timeout,
                 const TRequest &request,
                 grpc::CompletionQueue &completion_queue, const TMethod &method,
                 TCallback _callback)
                : callback(std::move(_callback)), context(), status(),
                  response(), rpc(), start(std::chrono::system_clock::now())
            {
                context.set_deadline(std::chrono::system_clock::now() +
                                     std::chrono::nanoseconds(timeout));
                rpc = method(stub, &context, request, &completion_queue);
            }
            /**
             * Callback to run when the RPC completes.
             */
            const TCallback callback;
            /**
             * RPC context.
             */
            grpc::ClientContext context;
            /**
             * Status of the callback. Filled on completion.
             */
            grpc::Status status;
            /**
             * The server's response. Filled on successful completion.
             */
            TResponse response;
            /**
             * gRPC object representing the RPC.
             */
            TRPC rpc;
            /**
             * Start time.
             */
            std::chrono::system_clock::time_point start;

        private:
            /*
             * Callback can be an implicitly converted Slot. Slot
             * manipulates reference counts on referenced SignalHandlers without
             * locking, so copying it outside of the main thread is unsafe.
             */
            FSW_DISALLOW_COPY_AND_ASSIGN(Call);
        };
        /**
         * Constructor.
         *
         * @param _endpoint_provider     Provides the service endpoint.
         * @param _stub_factory          Stub factory.
         * @param _callback_queue        Runs callbacks on the main thread.
         * @param _method                Bound Async* method to call.
         * @param _timeout               Timeout for all calls.
         * @param _max_outstanding_calls Max in-flight calls at any time.
         */
        GrpcClient(
            std::shared_ptr<GrpcEndpointProviderInterface> _endpoint_provider,
            std::shared_ptr<StubFactoryInterface> _stub_factory,
            DeferredCallbackQueue &_callback_queue, TMethod _method,
            const nano_t _timeout, const size_t _max_outstanding_calls)
            : endpoint_provider(_endpoint_provider),
              callback_queue(_callback_queue), method(std::move(_method)),
              timeout(_timeout), max_outstanding_calls(_max_outstanding_calls),
              completion_queue(), stub_factory(_stub_factory), last_tag(0),
              worker_thread(std::bind(&GrpcClient::worker, this))
        {
            gpr_global_config_set_grpc_poll_strategy("epoll1");
            gpr_global_config_set_grpc_dns_resolver("native");
        }
        /**
         * Initialize the client.
         *
         * @param builder Slate builder.
         * @param flow    Optional telemetry flow to add slate elements to.
         */
        bool init(SlateBuilder &builder, GroundNumericFlow *flow)
        {
            FswAbortIfNot(is_rpc_initialized(), false);
            /*
             * Throughput metrics.
             */
            SlateBuilder count_builder = builder.sub_slate("count");
            SlateBuilder count_completed_builder =
                count_builder.sub_slate("completed");
            SlateBuilder count_failed_builder =
                count_builder.sub_slate("failed");
            FswAbortIfNot(count_builder.create("started.total", shard_nonsync,
                                               slate_read_only,
                                               metric_count_started_tok),
                          false);
            FswAbortIfNot(count_builder.create("skipped.total", shard_nonsync,
                                               slate_read_only,
                                               metric_count_skipped_tok),
                          false);
            FswAbortIfNot(count_builder.create("outstanding.total",
                                               shard_nonsync, slate_read_only,
                                               metric_count_outstanding_tok),
                          false);
            FswAbortIfNot(count_builder.create("new_stub", shard_nonsync,
                                               slate_read_only,
                                               metric_count_new_stub_tok),
                          false);
            FswAbortIfNot(count_completed_builder.create(
                              "total", shard_nonsync, slate_read_only,
                              metric_count_completed_tok),
                          false);
            FswAbortIfNot(count_completed_builder.create(
                              "succeeded", shard_nonsync, slate_read_only,
                              metric_count_succeeded_tok),
                          false);
            FswAbortIfNot(count_failed_builder.create("total", shard_nonsync,
                                                      slate_read_only,
                                                      metric_count_failed_tok),
                          false);
            FswAbortIfNot(count_failed_builder.create("timeout", shard_nonsync,
                                                      slate_read_only,
                                                      metric_count_timeout_tok),
                          false);
            FswAbortIfNot(count_failed_builder.create("error", shard_nonsync,
                                                      slate_read_only,
                                                      metric_count_error_tok),
                          false);
            /*
             * Latency metrics.
             */
            SlateBuilder latency_builder = builder.sub_slate("latency");
            FswAbortIfNot(latency_builder.create("last_nanos", shard_nonsync,
                                                 slate_read_only,
                                                 metric_latency_last_nanos_tok),
                          false);
            FswAbortIfNot(latency_builder.create(
                              "total_nanos", shard_nonsync, slate_read_only,
                              metric_latency_total_nanos_tok),
                          false);
            /*
             * Status metrics.
             */
            SlateBuilder status_builder = builder.sub_slate("status");
            FswAbortIfNot(status_builder.create("last", shard_nonsync,
                                                slate_read_only,
                                                metric_status_last_tok),
                          false);
            FswAbortIfNot(status_builder.create("last_error", shard_nonsync,
                                                slate_read_only,
                                                metric_status_last_error_tok),
                          false);
            /*
             * Initialize slate.
             */
            slate = builder.slate(slate_no_validation);
            /*
             * Initialize optional ground telemetry flow.
             */
            if (flow)
            {
                FswAbortIfNot(flow->add_slate_element(metric_count_started_tok),
                              false);
                FswAbortIfNot(flow->add_slate_element(metric_count_skipped_tok),
                              false);
                FswAbortIfNot(
                    flow->add_slate_element(metric_count_outstanding_tok),
                    false);
                FswAbortIfNot(
                    flow->add_slate_element(metric_count_completed_tok), false);
                FswAbortIfNot(
                    flow->add_slate_element(metric_count_succeeded_tok), false);
                FswAbortIfNot(flow->add_slate_element(metric_count_failed_tok),
                              false);
                FswAbortIfNot(flow->add_slate_element(metric_count_timeout_tok),
                              false);
                FswAbortIfNot(flow->add_slate_element(metric_count_error_tok),
                              false);
                FswAbortIfNot(
                    flow->add_slate_element(metric_latency_last_nanos_tok),
                    false);
                FswAbortIfNot(
                    flow->add_slate_element(metric_latency_total_nanos_tok),
                    false);
                FswAbortIfNot(flow->add_slate_element(metric_status_last_tok),
                              false);
                FswAbortIfNot(
                    flow->add_slate_element(metric_status_last_error_tok),
                    false);
            }
            if (!stub_factory)
            {
                stub_factory = GrpcStubFactory<TService>::create();
            }
            FswAbortIfNot(stub_factory, false);
            return true;
        }
        FSW_DISALLOW_COPY_AND_ASSIGN(GrpcClient);
        /**
         * Worker thread entry point.
         */
        void worker()
        {
            /*
             * Read from the completion queue forever.
             */
            uintptr_t tag = 0;
            bool ok = false;
            while (completion_queue.Next(reinterpret_cast<void **>(&tag), &ok))
            {
                /*
                 * Record end time as soon as possible
                 */
                const auto end = std::chrono::system_clock::now();
                if (!ok)
                {
                    FswIfNot(ok);
                    continue;
                }
                /*
                 * Record metrics and run callback on main thread.
                 */
                callback_queue.enqueue(
                    std::bind(&GrpcClient::complete, this, tag, end));
            }
        }
        /**
         * Run a callback. Called from main thread via the callback_queue.
         *
         * @param tag Tag for the call to be completed.
         * @param end Complete time for call.
         */
        void complete(uintptr_t tag, std::chrono::system_clock::time_point end)
        {
            /*
             * Grab a pointer to this call.
             */
            auto it = outstanding_calls.find(tag);
            if (FswIf(it == outstanding_calls.end()))
            {
                return;
            }
            std::unique_ptr<Call> call = std::move(it->second);
            outstanding_calls.erase(it);
            /*
             * Record metrics.
             */
            --slate[metric_count_outstanding_tok];
            const nano_t latency_nanos = (end - call->start).count();
            ++slate[metric_count_completed_tok];
            slate[metric_status_last_tok] = call->status.error_code();
            slate[metric_latency_last_nanos_tok] = latency_nanos;
            slate[metric_latency_total_nanos_tok] += latency_nanos;
            if (call->status.ok())
            {
                ++slate[metric_count_succeeded_tok];
            }
            else
            {
                ++slate[metric_count_failed_tok];
                slate[metric_status_last_error_tok] = call->status.error_code();
                if (call->status.error_code() ==
                    grpc::StatusCode::DEADLINE_EXCEEDED)
                {
                    ++slate[metric_count_timeout_tok];
                }
                else
                {
                    ++slate[metric_count_error_tok];
                }
            }
            /*
             * On failed calls, we re-create our stub (and its associated
             * channel) to avoid issues with the underlying kernel / gRPC
             * timeouts interfering with our desired timeout.
             *
             * Only reset/recreate the stub when the call completes since
             * the stub an RPC is created with must live for as long as
             * the RPC.
             */
            const bool force_new_stub = !call->status.ok();
            if (stub_factory->NewStub(*endpoint_provider, stub, force_new_stub))
            {
                ++slate[metric_count_new_stub_tok];
            }
            /*
             * Run the callback.
             */
            FswIfNot(call->callback(std::move(call->status),
                                    std::move(call->response)));
        }
        /**
         * gRPC service endpoint provider.
         */
        std::shared_ptr<GrpcEndpointProviderInterface> endpoint_provider;
        /**
         * Queue for running callbacks on the main thread.
         */
        DeferredCallbackQueue &callback_queue;
        /**
         * Underlying autogenerated Async* method.
         */
        TMethod method;
        /**
         * Timeout for all RPCs.
         */
        nano_t timeout;
        /**
         * The maximum number of allowed in-flight RPCs.
         */
        const size_t max_outstanding_calls;
        /**
         * gRPC completion queue to read completed RPCs from.
         */
        grpc::CompletionQueue completion_queue;
        /**
         * Stub factory.
         */
        std::shared_ptr<StubFactoryInterface> stub_factory;
        /**
         * gRPC Stub used to make calls.
         */
        std::shared_ptr<StubInterface> stub;
        /**
         * Unique identifier of the last RPC to be issued.
         */
        uintptr_t last_tag;
        /**
         * Map of (tag, in flight RPC) pairs.
         */
        std::map<uintptr_t, std::unique_ptr<Call>> outstanding_calls;
        /**
         * Metric slate.
         */
        Slate slate;
        /**
         * Number of RPCs ever started.
         */
        WriteToken<UINT64> metric_count_started_tok;
        /**
         * Number of RPCs skipped because too many requests were in flight.
         */
        WriteToken<UINT64> metric_count_skipped_tok;
        /**
         * Number of RPCs currently in flight.
         */
        WriteToken<UINT64> metric_count_outstanding_tok;
        /**
         * Number of RPCs completed, whether or not they suceeded.
         */
        WriteToken<UINT64> metric_count_completed_tok;
        /**
         * Number of RPCs that completed successfully.
         */
        WriteToken<UINT64> metric_count_succeeded_tok;
        /**
         * Number of RPCs that failed for any reason.
         */
        WriteToken<UINT64> metric_count_failed_tok;
        /**
         * Number of RPCs that timed out.
         */
        WriteToken<UINT64> metric_count_timeout_tok;
        /**
         * Number of RPCs where the server returned an error.
         */
        WriteToken<UINT64> metric_count_error_tok;
        /**
         * Number of times the stub was recreated.
         */
        WriteToken<UINT64> metric_count_new_stub_tok;
        /**
         * Latency of the last completed RPC.
         */
        WriteToken<UINT64> metric_latency_last_nanos_tok;
        /**
         * Total latency of all completed RPCs.
         */
        WriteToken<UINT64> metric_latency_total_nanos_tok;
        /**
         * Status of the last completed RPC.
         */
        WriteToken<UINT64> metric_status_last_tok;
        /**
         * Status of the last failed RPC.
         */
        WriteToken<UINT64> metric_status_last_error_tok;
        /**
         * Thread responsible for processing the CompletionQueue.
         */
        std::thread worker_thread;
        friend struct ::GrpcClientHarness;
    };
    /**
     * Free function for constructing GrpcClients, provided for convenience (it
     * can infer some template parameters and does not need to be preceded by
     * GrpcClient scoping).
     *
     * @tparam TService GRPC Service class
     * @tparam TRequest request type (inferred)
     * @tparam TResponse response type (inferred)
     *
     * @param _endpoint_provider     Provides the service endpoint.
     * @param _callback_queue        Runs callbacks on the main thread.
     * @param _method                Async* method to call.
     * @param builder                Slate builder.
     * @param _timeout               Timeout for all calls. Default one
     *                               second.
     * @param _max_outstanding_calls Max in-flight calls at any time.
     *                               Default 1.
     * @param flow                   Optional telemetry flow for metrics.
     * @param _stub_factory          Optional factory to create new stubs.
     *                               If null, GrpcStubFactory<Interface>
     *                               will be used.
     */
    template <typename TService, typename TRequest, typename TResponse>
    Handle<GrpcClient<TService, TRequest, TResponse>> create_grpc_client(
        std::shared_ptr<GrpcEndpointProviderInterface> _endpoint_provider,
        DeferredCallbackQueue &_callback_queue,
        std::unique_ptr<grpc::ClientAsyncResponseReaderInterface<TResponse>> (
            TService::StubInterface::*_method)(grpc::ClientContext *,
                                               const TRequest &,
                                               grpc::CompletionQueue *),
        SlateBuilder &builder, const nano_t _timeout = billion,
        const size_t _max_outstanding_calls = 1,
        GroundNumericFlow *flow = nullptr,
        std::shared_ptr<GrpcStubFactoryInterface<TService>> _stub_factory = {})
    {
        using client_t = GrpcClient<TService, TRequest, TResponse>;
        return client_t::create(_endpoint_provider, _callback_queue, _method,
                                builder, _timeout, _max_outstanding_calls, flow,
                                _stub_factory);
    }
} // namespace Drone
#endif